// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
................................
................................
................................
................................
................................
................................
.............f..................
...........1fcf.................
..........11fccff...............
...........1fccccf..............
.........111fcccccf.............
........f..1fccccccffff.........
......1fcf.11fcccccccccff.......
.....11fccff1ffccccccccccff.....
........fcccfccfcccccfffffcff...
.........fccccccccccf66666fccff.
.........fccccccccccf66666fccff.
........fcccfccfcccccfffffcff...
.....11fccff1ffccccccccccff.....
......1fcf.11fcccccccccff.......
........f..1fccccccffff.........
.........111fcccccf.............
...........1fccccf..............
..........11fccff...............
...........1fcf.................
.............f..................
................................
................................
................................
................................
................................
................................
`;
            case "image2":
            case "myImage0":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . f f . . . . . . . . . . . 
. . f 5 5 f . . . . . . . . . . 
. f 5 . . 5 . . . . . . . . . . 
. f 5 . . 5 . . . . . . . . . . 
. f 5 . . 5 . . . . . . . . . . 
. f 5 . . 5 . . . . . . . . . . 
. . f 5 5 f . . . . . . . . . . 
. . . f f 5 5 . 5 . . . . . . . 
. . . . . 5 5 . 5 . . . . . . . 
. . . . . 5 5 . 5 . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
